# Generated by Django 2.0.7 on 2018-07-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='m',
        ),
        migrations.RemoveField(
            model_name='city',
            name='pro',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.RemoveField(
            model_name='xian',
            name='cy',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Xian',
        ),
    ]
